package com.vksql.network.worker;

import java.nio.file.Path;

/**
 * Worker: executes tasks assigned by the coordinator.
 *
 * Responsibilities:
 * 1. Register with coordinator (send heartbeats)
 * 2. Receive TaskRequest from coordinator
 * 3. Execute locally (scan local data, filter, aggregate)
 * 4. Return TaskResult (or shuffle to other workers)
 *
 * Each worker owns a partition of the data (subset of .vkql files).
 *
 * Implementation steps:
 * - Extend WorkerServiceGrpc.WorkerServiceImplBase (generated by protobuf)
 * - Override executeTask() and heartbeat() methods
 * - Use local execution engine (ScanOperator, FilterOperator, etc.)
 */
public class Worker {

    private final String workerId;
    private final Path dataDirectory;  // where this worker's .vkql files live
    private final int port;
    private final String coordinatorAddress;

    public Worker(String workerId, Path dataDirectory, int port, String coordinatorAddress) {
        this.workerId = workerId;
        this.dataDirectory = dataDirectory;
        this.port = port;
        this.coordinatorAddress = coordinatorAddress;
    }

    // TODO: Start gRPC server, start heartbeat thread
    public void start() {
        // 1. Start gRPC server for receiving tasks
        // Server server = ServerBuilder.forPort(port)
        //     .addService(new WorkerServiceImpl(this))
        //     .build()
        //     .start();

        // 2. Start heartbeat thread (send heartbeat to coordinator every 5s)
        // Thread.startVirtualThread(this::heartbeatLoop);
    }

    /**
     * Execute a task locally using the existing execution engine.
     * This reuses everything you already built — ScanOperator, FilterOperator, etc.
     */
    public Object executeTask(String tableName, String filterColumn, String filterOp,
                              long filterValue, String groupByColumn, String aggFunction,
                              String aggColumn) {
        // TODO:
        // 1. Find the .vkql file for this table in dataDirectory
        // 2. Build operator chain (Scan → Filter → Aggregate)
        // 3. Execute and collect results
        // 4. Return as RecordBatch (or serialize to protobuf)
        return null;
    }

    public String getWorkerId() { return workerId; }
    public Path getDataDirectory() { return dataDirectory; }
}
