package com.vksql.network.coordinator;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Coordinator: the "brain" of the distributed query engine.
 *
 * Responsibilities:
 * 1. Receive SQL from client
 * 2. Parse + plan the query
 * 3. Split into tasks (one per worker per stage)
 * 4. Assign tasks to workers
 * 5. Collect results
 * 6. Return final result to client
 *
 * Implementation steps:
 * - Extend CoordinatorServiceGrpc.CoordinatorServiceImplBase (generated by protobuf)
 * - Override executeQuery() method
 * - Use WorkerRegistry to track live workers
 * - Use TaskScheduler to assign tasks
 */
public class Coordinator {

    private final WorkerRegistry workerRegistry;
    private final ConcurrentHashMap<String, QueryState> activeQueries = new ConcurrentHashMap<>();
    private final int port;

    public Coordinator(int port) {
        this.port = port;
        this.workerRegistry = new WorkerRegistry();
    }

    // TODO: Start gRPC server, implement ExecuteQuery RPC
    public void start() {
        // Server server = ServerBuilder.forPort(port)
        //     .addService(new CoordinatorServiceImpl(this))
        //     .build()
        //     .start();
    }

    public WorkerRegistry getWorkerRegistry() {
        return workerRegistry;
    }

    /**
     * Plan a query into distributed stages.
     * Stage 0: Scan + Filter + Partial Aggregate (on each worker)
     * Stage 1: Final Aggregate (gather results from all workers)
     */
    public List<TaskAssignment> planDistributed(String sql) {
        // TODO:
        // 1. Parse SQL → plan tree
        // 2. Determine which workers have which data partitions
        // 3. Create TaskRequest for each worker
        // 4. Return list of assignments
        return List.of();
    }
}
