package com.vksql.network.shuffle;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

/**
 * ShuffleServer: receives intermediate batches from other workers.
 *
 * Implements ShuffleServiceGrpc.ShuffleServiceImplBase (generated by protobuf).
 * Incoming batches are queued and consumed by the next stage's operator.
 *
 * Back-pressure: if the queue is full, gRPC flow control kicks in
 * and the sender slows down automatically.
 */
public class ShuffleServer {
    private final BlockingQueue<Object> incomingBatches = new LinkedBlockingQueue<>(1000);

    // TODO: implement gRPC service
    // Override PushBatch streaming RPC
    // For each batch received: incomingBatches.put(batch)

    /**
     * Called by the local executor to get the next shuffled batch.
     */
    public Object nextBatch() throws InterruptedException {
        return incomingBatches.take(); // blocks until data arrives
    }

    public boolean hasData() {
        return !incomingBatches.isEmpty();
    }
}
